name: Hues A339X VKG Livery Package Development
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/hues-a339x-vkg-dev.yml'
      - 'hues-a339x-vkg/**'
      - 'scripts/build-hues-a339x-vkg.js'
      - 'scripts/build-hues-a339x-vkg.sh'
      - 'scripts/fragment-hues-a339x-vkg.js'
      - 'scripts/install-source-hues-a339x-vkg.js'
      - 'scripts/cdn.sh'
      - 'scripts/git_build_info.js'
      - 'scripts/setup.sh'
      - 'igniter.config.mjs'
      - 'package.json'
      - 'package-lock.json'

jobs:
  build_hues_a339x_vkg_4k:
    # Prevent running this on forks
    if: github.repository_owner == 'headwindsim'
    name: 'Build HUES A339X VKG 4K Livery Package'
    runs-on: ubuntu-latest
    env:
      A32NX_PRODUCTION_BUILD: 1
      A32NX_INSTRUMENTS_BUILD_WORKERS: 2
      ZIP_NAME: hues-livery-a339x-sunclass-package-4k-dev.zip
      BUILD_DIR_NAME: dev
      CLOUDFLARE_WORKER_PASSWORD: ${{ secrets.CLOUDFLARE_WORKER_PASSWORD }}
      CDN_BUCKET_DESTINATION: addons/hues-livery-a339x-sunclass-package-4k/dev
    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v4.1
        with:
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-large-packages: 'true'
          remove-cached-tools: 'true'
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set BUILT_DATE_TIME
        run: echo "BUILT_DATE_TIME=$(date -u -Iseconds)" >> $GITHUB_ENV
      - name: Create .env file
        run: |
          echo A32NX_PRODUCTION_BUILD=1 >> .env
          echo CLIENT_ID=${{ secrets.NAVIGRAPH_CLIENT_ID }} >> .env
          echo CLIENT_SECRET=${{ secrets.NAVIGRAPH_CLIENT_SECRET }} >> .env
          echo CHARTFOX_SECRET=${{ secrets.CHARTFOX_SECRET }} >> .env
          echo SENTRY_DSN=${{ secrets.SENTRY_DSN }} >> .env
          echo BUILD_DIR_NAME=${{ env.BUILD_DIR_NAME }} >> .env
          echo LOCALAZY_READ_KEY=${{ secrets.LOCALAZY_READ_KEY }} >> .env
      - name: Setup Package
        run: |
          ./scripts/dev-env/run.sh ./scripts/setup.sh --clean
      - name: Build Livery Package
        run: |
          ./scripts/dev-env/run.sh ./scripts/build-hues-a339x-vkg.sh --no-tty -j 4 -4k
          docker system prune -af
      - name: Build ZIP files
        run: |
          node ./scripts/fragment-hues-a339x-vkg.js
          cp ./hues-a339x-vkg/out/build-modules/modules.json ./hues-a339x-vkg/out/hues-livery-a339x-sunclass-package/install.json
          node ./scripts/install-source-hues-a339x-vkg.js
          mkdir ./${{ env.BUILD_DIR_NAME }}
          cd ./hues-a339x-vkg/out/
          zip -r ../../${{ env.BUILD_DIR_NAME }}/${{ env.ZIP_NAME }} ./hues-livery-a339x-sunclass-package/
          cd ../../
      - name: Upload to CloudFlare CDN
        run: |
          ./scripts/cdn.sh $CDN_BUCKET_DESTINATION ./hues-a339x-vkg/out/build-modules
  build_hues_a339x_vkg_8k:
    # Prevent running this on forks
    if: github.repository_owner == 'headwindsim'
    name: 'Build HUES A339X VKG 8K Livery Package'
    runs-on: ubuntu-latest
    env:
      A32NX_PRODUCTION_BUILD: 1
      A32NX_INSTRUMENTS_BUILD_WORKERS: 2
      ZIP_NAME: hues-livery-a339x-sunclass-package-8k-dev.zip
      BUILD_DIR_NAME: dev
      CLOUDFLARE_WORKER_PASSWORD: ${{ secrets.CLOUDFLARE_WORKER_PASSWORD }}
      CDN_BUCKET_DESTINATION: addons/hues-livery-a339x-sunclass-package-8k/dev
    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v4.1
        with:
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-large-packages: 'true'
          remove-cached-tools: 'true'
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set BUILT_DATE_TIME
        run: echo "BUILT_DATE_TIME=$(date -u -Iseconds)" >> $GITHUB_ENV
      - name: Create .env file
        run: |
          echo A32NX_PRODUCTION_BUILD=1 >> .env
          echo CLIENT_ID=${{ secrets.NAVIGRAPH_CLIENT_ID }} >> .env
          echo CLIENT_SECRET=${{ secrets.NAVIGRAPH_CLIENT_SECRET }} >> .env
          echo CHARTFOX_SECRET=${{ secrets.CHARTFOX_SECRET }} >> .env
          echo SENTRY_DSN=${{ secrets.SENTRY_DSN }} >> .env
          echo BUILD_DIR_NAME=${{ env.BUILD_DIR_NAME }} >> .env
          echo LOCALAZY_READ_KEY=${{ secrets.LOCALAZY_READ_KEY }} >> .env
      - name: Setup Package
        run: |
          ./scripts/dev-env/run.sh ./scripts/setup.sh --clean
      - name: Build Livery Package
        run: |
          ./scripts/dev-env/run.sh ./scripts/build-hues-a339x-vkg.sh --no-tty -j 4
          docker system prune -af
      - name: Build ZIP files
        run: |
          node ./scripts/fragment-hues-a339x-vkg.js
          cp ./hues-a339x-vkg/out/build-modules/modules.json ./hues-a339x-vkg/out/hues-livery-a339x-sunclass-package/install.json
          node ./scripts/install-source-hues-a339x-vkg.js
          mkdir ./${{ env.BUILD_DIR_NAME }}
          cd ./hues-a339x-vkg/out/
          zip -r ../../${{ env.BUILD_DIR_NAME }}/${{ env.ZIP_NAME }} ./hues-livery-a339x-sunclass-package/
          cd ../../
      - name: Upload to CloudFlare CDN
        run: |
          ./scripts/cdn.sh $CDN_BUCKET_DESTINATION ./hues-a339x-vkg/out/build-modules